export const FETCH_INDO_CASUALTIES = 'FETCH_INDO_CASUALTIES'
export const FETCH_GLOBAL_CASUALTIES = 'FETCH_GLOBAL_CASUALTIES'

export const FETCH_INDO_REGION_DATA = 'FETCH_INDO_REGION_DATA'
export const FETCH_GLOBAL_REGION_DATA = 'FETCH_GLOBAL_REGION_DATA'

export const FETCH_NEWS = 'FETCH_NEWS'